import { IsNotEmpty, IsOptional, IsString, IsBoolean, IsEnum } from 'class-validator';
import { ActivityType, Level } from '@prisma/client';

export class CreateActivityDto {

  @IsNotEmpty({ message: 'O título é obrigatório.' })
  @IsString()
  title: string;

  @IsNotEmpty({ message: 'O level é obrigatório.' })
  @IsEnum(Level, { message: `O level deve ser um dos: ${Object.values(Level).join(', ')}` })
  level: Level;

  @IsOptional()
  @IsString({ message: 'A descrição deve ser uma string.' })
  description?: string;

  @IsNotEmpty({ message: 'O tipo de atividade é obrigatório.' })
  @IsEnum(ActivityType, { message: `O tipo deve ser um dos: ${Object.values(ActivityType).join(', ')}` })
  type: ActivityType;

  @IsOptional()
  options?: any;

  @IsOptional()
  @IsString({ message: 'A resposta correta deve ser uma string.' })
  correctAnswer?: string;

  @IsOptional()
  @IsString({ message: 'A URL da mídia deve ser uma string.' })
  mediaUrl?: string;

  @IsOptional()
  @IsString({ message: 'O campo createdBy deve ser uma string.' })
  createdBy?: string;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;

  @IsOptional()
  @IsString({ message: 'groupId deve ser uma string.' })
  groupId?: string;
}
