export type LevelType = 'BASIC' | 'LOWER_INTERMEDIATE' | 'INTERMEDIATE' | 'UPPER_INTERMEDIATE' | 'ADVANCED';

export enum levelEnum {
  BASIC = 'BASIC',
  LOWER_INTERMEDIATE = 'LOWER_INTERMEDIATE',
  INTERMEDIATE = 'INTERMEDIATE',
  UPPER_INTERMEDIATE = 'UPPER_INTERMEDIATE',
  ADVANCED = 'ADVANCED'
}